INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('book', 'library', 600, 2, 104);

INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);
INSERT INTO users (name, age) VALUES ('bob', 31);

INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 3, 4);